version: 0.2

phases:
  pre_build:
    commands:
      - echo logging to Docker Hub
      - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
  build:
    commands:
      - echo building docker image
      - docker build -t my-app .

      - echo tagging image
      - docker tag my-app $DOCKER_USERNAME
  post_build:
    commands:
      - echo pushing image to dockerhub
      - docker push $DOCKER_USERNAME/my-app
